language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mpragnarok/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mpragnarok/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    # elastic beanstalk app name
    app: "docker-react"
    env: "Dockerreact"
    # s3 bucket name
    bucket_name: "elasticbeanstalk-us-east-2-544101413601"
    # elastic beanstalk app name
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
