FROM node:alpine

WORKDIR '/app'

COPY package.json .
# RUN npm config set unsafe-perm true
# Give owner rights to the current user
# RUN chown -Rh $user:$user /app
# USER $user

RUN npm install

COPY . . 
# RUN chown -R node: /webapp
USER node

CMD ["npm", "run", "start"]